

services:
  frontend:
    build:
      context: .
      dockerfile: deploy/docker/frontend.Dockerfile
      args:
        - NEXT_PUBLIC_OPENWEATHER_API_KEY=${NEXT_PUBLIC_OPENWEATHER_API_KEY}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:5002}
      cache_from:
        - nish714/weatherly-frontend:buildcache
    image: nish714/weatherly-frontend:v1.0.3
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_OPENWEATHER_API_KEY=${NEXT_PUBLIC_OPENWEATHER_API_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:5002}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weatherly-network

  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend.Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - PORT=${PORT:-5002}
        - CORS_ORIGINS=${CORS_ORIGINS:-*}
        - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
        - BASE_URL=${BASE_URL:-http://localhost}
        - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
        - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
        - CACHE_TTL=${CACHE_TTL:-1800000}
      cache_from:
        - nish714/weatherly-backend:buildcache
    image: nish714/weatherly-backend:v1.0.3
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5002}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - BASE_URL=${BASE_URL:-http://localhost}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - CACHE_TTL=${CACHE_TTL:-1800000}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5002/api/v1/weather/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weatherly-network

networks:
  weatherly-network:
    name: weatherly-network
    driver: bridge