apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-config
data:
  NODE_ENV: "production"
  CORS_ORIGINS: "*"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "100"
  CACHE_TTL: "1800000"
  BASE_URL: "https://api.openweathermap.org/data/2.5"
  PORT: "5000"
  NEXT_PUBLIC_API_BASE_URL: "http://k8s-weatherapp-9192b5bb96-515230204.us-east-1.elb.amazonaws.com/api/v1/weather"
  NEXT_PUBLIC_BASE_URL: "http://k8s-weatherapp-9192b5bb96-515230204.us-east-1.elb.amazonaws.com"

# secrets.yaml
  apiVersion: v1
kind: Secret
metadata:
  name: weather-app-secret
type: Opaque
data:
  OPENWEATHER_API_KEY: YTc0ZTM2OGYyMmVkNWE4MmVhOTliZjU0MzNkZGViZmM=
  NEXT_PUBLIC_OPENWEATHER_API_KEY: YTc0ZTM2OGYyMmVkNWE4MmVhOTliZjU0MzNkZGViZmM=